spring:
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
#    redis:
#      host:
server:
  context-path: /sso-client-two
  port: 8084

datasource:
  mysqlConnect:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.1.249.198:3306/aiddos20190121?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    maxLifetime: 600000
    idleTimeout: 300000
    maximumPoolSize: 100
    minimumIdle: 50
    username: aiddos
    password: asiainfo
sso:
  service:
    url: http://localhost:8082/sso-service/index
  client:
    url: redirect_url
  token:
    url: http://localhost:8082/sso-service/checkToken
  logout:
      url: http://localhost:8082/sso-service/logout